### ISSUE TITLE
Add opportunity to configure the error handler - FOR DECOMPOSITION

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-dark#103]
Позволить пользователю определять поведение в случае различных ошибок (пример как это сделано в restTemplate https://www.baeldung.com/spring-rest-template-error-handling ) 

Сделать как на примере Спринга (поговорить с @vitaly-dukhov  про детали)

1. Implementation
2. Cover with tests (for instance: split logic for client and server errors)
3. Add an article into documentation

**Comment by ElenaPoduzova** [comment]
Demo has been done.
