### ISSUE TITLE
Cookies: Missing functionality

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-dark#105]
Following problems were identified:
Missing functionality
-     to get detailed cookies (analog to RestAssured detailedCookies()) e.g. to get expiration date 
-     to pass cookie without value (+ handle such cookie in response) 
-     to pass multi value cookie 
-     to pass cookie different from MapArray (e.g. as pair of Strings, Map, several pairs etc - a lot of ways in RestAssured) 

Expected:
Check if every bullet is actual and cannot be resolved with existed framework API
Find solution for every identified problem remaining in list
Discuss proposed solution w/Team if someone from review team agrees, create a dedicated task for implementation and link it to the current issue (that include implementation of the proposed solution, test covering and documentation creation)

**Comment by BelAn97** [comment]
done by Tatiana
