### ISSUE TITLE
Response: Missing functionality

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-dark#108]
Following problems were identified:
- At the moment we have no methods to get Status Line (no methods to get status code, only via variable response.status.code - is it needed?) 
- Not possible to send Form Params with POST request 
- No dark methods to get body (only if use public ‘body’ field) 
- No dark methods to parse body as xml, json, html, get asByteArray/InputStream etc. All possible only via raResponse() method that redirects to RestAssured methods.  

Expected:
1. Check if every bullet is actual and cannot be resolved with existed framework API
2. Find solution for every identified problem remaining in list
3. Discuss proposed solution w/Team if someone from review team agrees, create a dedicated task for implementation  and link it to the current issue (that include implementation of the proposed solution, test covering and documentation creation)

**Comment by ElenaPoduzova** [comment]
Demo has been done.
