### ISSUE TITLE
Delete: Missing functionality - FOR INVESTIGATION, GROOMING AND DECOMPOSITION

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-dark#109]
- At the moment JDI Dark cannot add ContentType depend on request type automatically. AS WA specified @ContentType was added in service layer for the request (deleteSupportsStringBody test) 
- There is no possibility to set request params in the request, only via queryParams (bodyHamcrestMatcherWithoutKey test) 
- no dark methods to check body – only via assertThat() and ValidatableResponse RestAssured methods 
- Common: RestResponse doRequest do not throw full stack trace 

Contact w/ @BelAn97 for implementation details

Expected:
1. Implement proposed functionality that eliminates up mentioned disadvantages
2. Cover with tests
3. Add an article into documentation

**Comment by BelAn97** [comment]
done by Yulia
