### ISSUE TITLE
Post: Missing functionality

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-dark#111]
- No special method to send queryParam, now I must to send them in this way:        запрос.call(requestData(d -> { 

                 d.queryParams.add(new Object[][]{{"firstName", "John"},                    {"lastName", "Doe"}}); 
             }));    Also no posibbility to append queryParam 
- No methods to check content-type in response 
- Impossible to pass in Body next types: InputStream, Int, Float, Double, Short, Boolean,  Byte 
- Cannot specify in ContentType String (for example @ContentType("application/json"). 
- Cannot automatic specify Content-type when we send it just in header in this way @Header(name = "accept", value = "application/json") 

Contact w/ @BelAn97 for implementation details

Expected:

1. Implement proposed functionality that eliminates up mentioned disadvantages
2. Cover with tests
3. Add an article into documentation

**Comment by ElenaPoduzova** [comment]
Demo has been done.
