### ISSUE TITLE
ParamTest: Missing functionality

### ISSUE THREAD

**Issue by BelAn97** [jdi-testing/jdi-dark#124]
Following problems were identified:
   Path params ("{param1}/{param2}" are linked to baseUri - for this reason user can set path params only using replace in baseUri
    There is not special method to send request params (rest assured test noValueParamWhenUsingParamWithGetRequest cannot be implemented in jdi-dark) 

    There is no special method to send form params 

    There is no special method to send multiparts 

    It is impossible to send query param in url, when we need to send param name without value (for example “?some1=one&some2” - this is trimmed now) - rootcause is path is not sent to RequestSpecificationImpl.groovy in rest assured from jdi-dark code and query params are trimmed, jdi-dark getSpec() or RequestData (?) should be changed to support this case 

    It is impossible to send only name in query params 

Expected:
Check if every bullet is actual and cannot be resolved with existed framework API
Find solution for every identified problem remaining in list
Discuss proposed solution w/Team if someone from review team agrees, create a dedicated task for implementation and link it to the current issue (that include implementation of the proposed solution, test covering and documentation creation)

**Comment by ElenaPoduzova** [comment]
Demo has been done.
