### ISSUE TITLE
PathParam: Missing functionality

### ISSUE THREAD

**Issue by BelAn97** [jdi-testing/jdi-dark#125]
Following problems were identified:

    Not throw IllegalArgumentException when wrong path params (now throw Runtime exception) 

    Can’t pass INT type to value path param (now in this case throw Runtime Exception) 

    Can’t pass nonStandardChars with path param(for example \\$£@\"){¤$ , John: å) 

    Can’t pass unnamed path param (for example in restassured get("http://www.google.se/search?q={query}&hl=en", "query")) 

    Failed when pass space in value(example - requestPathParams(new Object[][]{{"firstName", "John"}, {"lastName", " "}} 

Expected:

    Check if every bullet is actual and cannot be resolved with existed framework API
    Find solution for every identified problem remaining in list
    Discuss proposed solution w/Team if someone from review team agrees, create a dedicated task for implementation and link it to the current issue (that include implementation of the proposed solution, test covering and documentation creation)

**Comment by hellokitties** [comment]
+ now in log url  view in this case http://localhost:8080/{firstName}/{lastName},

**Comment by ElenaPoduzova** [comment]
Demo has been done.
