### ISSUE TITLE
Create test documentation for one of the existion opensource Service(Report Portal ?)

### ISSUE THREAD

**Issue by troe88** [jdi-testing/jdi-dark#13]
Provide an example of different tests types for one of the Service;

1. Integration
2. Contract 
3. Component (mocking?)

Ask @YuliaAtlasova for review this tests.

Services:
- trello - https://developers.trello.com/reference/#actionsidmember
- https://docs.postman-echo.com
- reportportal

**Comment by ziforigin** [comment]
I'm doing a set of tests for https://reqres.in/ (REST)

**Comment by BelAn97** [comment]
done
