### ISSUE TITLE
Add examples to use precondition requestData

### ISSUE THREAD

**Issue by BelAn97** [jdi-testing/jdi-dark#130]

**Comment by BelAn97** [comment]
example 1:
1. add data provider with requestData and  expectations
2. add parametrised test using predefined data provider
example 2:
1. create file (csv) with some request data parameters and expectations
2. add data provider which convert csv data to requestData and expectations
2. add parametrised test using data provider

**Comment by ElenaPoduzova** [comment]
Demo has been done.
