### ISSUE TITLE
Documentation for newcomers

### ISSUE THREAD

**Issue by troe88** [jdi-testing/jdi-dark#15]
Сделать как для JDI Light

**Comment by AlexeyGirin** [comment]
Пример

Это – «шапка» daily митингов проекта JDI; JDI - наш фрэймворк для UI и бэкэнд автоматизации.
Бизнес овнеры проекта: Алексей Гирин, Роман Иовлев, скрам мастер: Дмитрий Фенцик.

Репозиторий проекта: https://github.com/jdi-testing 
CODE:   https://github.com/jdi-testing/jdi-light  

Документация / сайт документации:  https://jdi-docs.github.io/jdi-light/#documentation 
Прочие «документальные» ссылки:              
1. https://jdi-docs.github.io/jdi-light 
2. https://jdi-docs.github.io/jdi-dark  
3. https://jdi-docs.github.io/jdi-light/?java#jdi-light-bdd-steps  
4. https://github.com/jdi-docs/jdi-light/blob/master/source/includes/_documentation.md 

JDI 1 Cucumber: https://github.com/epam/JDI/tree/master/Java/JDI/jdi-uitest-cucumber  

Тесты по Элементам в JDI Light (код):   
https://github.com/jdi-testing/jdi-light/tree/master/jdi-light-html-tests/src/test/java/io/github/epam/html/tests/elements 

Шаропапка для записей митингов и т.п. контента ( < ЛИНК_ДЛЯ_КЛИКАНЬЯ > ), то же самое – текстом:
https://epam-my.sharepoint.com/:f:/p/dmitrii_fentcik/EoPCi2cmTuRPshWdS6OEGu0BJvJOG6KP19VvXpweS79vuw

**Comment by ElenaPoduzova** [comment]
Demo has been done
