### ISSUE TITLE
Warning level codacy issues: Avoid unused imports such as {0}

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-dark#18]
Decomposition of #12

List of issues:
https://app.codacy.com/manual/jdi-testing/jdi-dark/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJXYXJuaW5nIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjUyNjIiXX1d

1. Learn the problem
2. Fix them if confirmed or suppress otherwise (ask @hellokitties - she know-how)

**Comment by BelAn97** [comment]
done
