### ISSUE TITLE
Warning level codacy issues: Unnecessary use of fully qualified name ''{0}'' due to existing {2}import ''{1}''

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-dark#194]
Unnecessary use of fully qualified name ''{0}'' due to existing {2}import ''{1}''

https://app.codacy.com/manual/jdi-testing/jdi-dark/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjU1NDEiXX1d

**Comment by ElenaPoduzova** [comment]
Done.
