### ISSUE TITLE
Warning level codacy issues:The {0} ''{1}'' has an NPath complexity of {2}

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-dark#195]
https://app.codacy.com/manual/jdi-testing/jdi-dark/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjU1NDgiXX1d

**Comment by ElenaPoduzova** [comment]
Need to ignore this issue.

**Comment by ElenaPoduzova** [comment]
Remove from codacy.

**Comment by ElenaPoduzova** [comment]
Done.
