### ISSUE TITLE
Warning level codacy issues: All classes, interfaces, enums and annotations must belong to a named package

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-dark#196]
https://app.codacy.com/manual/jdi-testing/jdi-dark/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjU1MTIiXX1d

**Comment by ElenaPoduzova** [comment]
Done.
