### ISSUE TITLE
Info level codacy issues: Use explicit scoping instead of the default package private level

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-dark#26]
Decomposition of #12

List of issues: https://app.codacy.com/manual/jdi-testing/jdi-dark/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJJbmZvIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjU1NjMiXX1d

1. Learn the problem
2. Fix them if confirmed or suppress otherwise (ask @hellokitties - she know-how)

**Comment by ElenaPoduzova** [comment]
Done.
