### ISSUE TITLE
Info level codacy issues: The {0} name ''{1}'' doesn''t match ''{2}''

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-dark#27]
Decomposition of #12

List of issues: https://app.codacy.com/manual/jdi-testing/jdi-dark/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJJbmZvIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjU0ODciXX1d
and
https://app.codacy.com/manual/jdi-testing/jdi-dark/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJJbmZvIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjUyNDYiXX1d

1. Learn the problem
2. Fix them if confirmed or suppress otherwise (ask @hellokitties - she know-how)

**Comment by ElenaPoduzova** [comment]
Done.
