### ISSUE TITLE
Info level codacy issues: Unnecessary use of fully qualified name ''{0}'' due to existing {2}import ''{1}''

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-dark#29]
Decomposition of #12

List of issues: https://app.codacy.com/manual/jdi-testing/jdi-dark/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJJbmZvIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjU1NDEiXX1d

1. Learn the problem
2. Fix them if confirmed or suppress otherwise (ask @hellokitties - she know-how)

**Comment by ElenaPoduzova** [comment]
Demo has been done.
