### ISSUE TITLE
Properties rules in json

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-dark#306]
Add all test properties description in JSON file like it is done in spring
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json

**Comment by hellokitties** [comment]
https://epam.sharepoint.com/:w:/r/sites/JDIDarkTeam/_layouts/15/doc.aspx?sourcedoc=%7B96c6370f-2b6d-41c9-af5e-c8a395326ccf%7D&action=edit&cid=d4308b07-7eb3-41ae-9499-765eacb997ec
list of  test properties

**Comment by AlexeyGirin** [comment]
1. Correct English text (replace "next" with "following", check plural)
2. Move file to JDI Dark core from example resources

**Comment by BelAn97** [comment]
Done by Julia
