### ISSUE TITLE
Сформировать список вопросов чего не понятно при взгляде на фрэймворк в первый раз

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-dark#309]

**Comment by olgaSovaDo** [comment]
1. It's not clear if path to the file is included into "myFile" or not
    @POST("/multipart/file")
    @MultiPart(controlName = "file", fileName = "myFile")
    public static RestMethod postMultipartFile;

2.  Are there any nice approach to implement the following restAssured stuff
        RestAssured.given()
                .header("Accept-Language", "es")
                .multiPart(new File(filesPath + fileName))
               .multiPart("trend", String.valueOf(postBody), "application/json")
                .config(RestAssured.config().sslConfig(
                 sslConfig().relaxedHTTPSValidation("TLS")))
                .auth().basic(user.name, user.password)
                .post(MiddlewareTrendsData.DOMAIN + MiddlewareTrendsData.POST_FILE_AND_FORM)

Is that the only option in Dark:
        RequestSpecification rs = postMultipartFile.getInitSpec()
                .multiPart(new File(filesPath + fileName))
                .multiPart("trend", String.valueOf(postBody), "application/json")
                .config(RestAssured.config().sslConfig(
                       sslConfig().relaxedHTTPSValidation("TLS")));
        RestResponse resp =  postMultipartFile.call(rs);

3.  Typos:
public class RequestDataFacrtory 
public void authBaseTestOverrideCredetialsWithCustomAuthScheme()

**Comment by BelAn97** [comment]
BDD section is out of date - it should to be updated

**Comment by AlexeyGirin** [comment]
Done.
