### ISSUE TITLE
Validate JDI-DARK "performance" functionality. Compare results with Jmeter or Gatling

### ISSUE THREAD

**Issue by troe88** [jdi-testing/jdi-dark#31]

**Comment by VShutkina** [comment]
JDIDarkPerfomanse results for ServiceExample (getInfo and Post)
[JDIDarkPerfomanse results.docx](https://github.com/jdi-testing/jdi-dark/files/4107798/JDIDarkPerfomanse.results.docx)

**Comment by AlexeyGirin** [comment]
Demo has been done.
