### ISSUE TITLE
Describe @multipart and @post annotation in the documentation

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-dark#335]
It's not clear if path to the file is included into "myFile" or not
@post("/multipart/file")
@multipart(controlName = "file", fileName = "myFile")
public static RestMethod postMultipartFile;

Please describe them in the documentation.
Review if we have another annotations not described and describe them as well.
Contact w/ @BelAn97 for details

**Comment by BelAn97** [comment]
Done by Olga
