### ISSUE TITLE
Create documentation for sending request with many parameters

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-dark#336]
Original message from @olgaSovaDo :

Are there any nice approach to implement the following restAssured stuff
RestAssured.given()
    .header("Accept-Language", "es")
    .multiPart(new File(filesPath + fileName))
    .multiPart("trend", String.valueOf(postBody), "application/json")
    .config(RestAssured.config().sslConfig(
    sslConfig().relaxedHTTPSValidation("TLS")))
    .auth().basic(user.name, user.password)
    .post(MiddlewareTrendsData.DOMAIN + MiddlewareTrendsData.POST_FILE_AND_FORM)

Is that the only option in Dark?
RequestSpecification rs = postMultipartFile.getInitSpec()
 .multiPart(new File(filesPath + fileName))
 .multiPart("trend", String.valueOf(postBody), "application/json")
 .config(RestAssured.config().sslConfig(
 sslConfig().relaxedHTTPSValidation("TLS")));
 RestResponse resp = postMultipartFile.call(rs);

/endOfMessage

Please create an article in the documentation that explains that in details based on @BelAn97  
example:
RestResponse resp = Service.postMultipartFile.call(rd -> {
rd.setMultiPart(new MultiPartSpecBuilder(new File(filesPath + fileName));
rd.setMultiPart(new MultiPartSpecBuilder(String.valueOf(postBody)).controlName("trend").mimeType("application/json"));
})

**Comment by BelAn97** [comment]
Done by Olga.
