### ISSUE TITLE
Update JDI Dark BDD Steps article

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-dark#339]
1. Now all examples are outdated and need to be refreshed with new versions.
2. The color schema should be also corrected in the same manner as it is for JDI Light BDD Steps (see - https://jdi-docs.github.io/jdi-light/#jdi-light-bdd-steps)
3. Add more sense to the description to make it more clear

**Comment by BelAn97** [comment]
Done by Julia
