### ISSUE TITLE
Review authorization functionality

### ISSUE THREAD

**Issue by troe88** [jdi-testing/jdi-dark#34]
We have to ask the question:
What kind of authorization technique implemented in JDI-DARK ?

1. Есть несколько популярных видов авторизации - надо понять удобно ли ими пользоваться в JDI Dark
2. Написать тест на каждый тип авторизации (возможно на нескольких внешних сервисах)
3. Если какие-то типы авторизации не поддерживаются - созадать таску на имплементацию поддержки в JDI Dark
4. Какую-то поддержку можно сделать удобнее - создать таск на улучшение этого типа

**Comment by BelAn97** [comment]
done
