### ISSUE TITLE
Update documentation for Repeatable Annotations

### ISSUE THREAD

**Issue by BelAn97** [jdi-testing/jdi-dark#348]
Remove @Method,
Using repeatable annotations:
    @GET("/cookie")
    @Cookie(name = "username", value = "John")
    @Cookie(name = "token", value = "1234")
    public static RestMethod getCookieWithCookies;

**Comment by olgaSovaDo** [comment]
PR for this improvement https://github.com/jdi-testing/jdi-dark/pull/349

**Comment by BelAn97** [comment]
Done by Olga
