### ISSUE TITLE
Create rest-assured like tests

### ISSUE THREAD

**Issue by troe88** [jdi-testing/jdi-dark#35]
#45 - ErrorMessageTest 
#46 - CookieTest 
#49 - ContentTypeTest
#50 - AdvancedValidationTest
#51 - BodyWithCustomContentTypeTest
#52 - PathArgumentsDemoTest
#47 - HeaderTest
#48 - JSONGetTest
#53 - JSONPostTest
#54 - ResponseTest
#55 - DeleteTest
#56 - SSLTest
#57 - ParamTest
#58 - ConfigTest
#59 - ObjectMappingTest
#60 - HttpClientConfigTest
#61 - UriValidatorTest
#62 - LoggingTest

**Comment by VShutkina** [comment]
List of tests:
ErrorMessageTest
CookieTest
ContentTypeTest
AdvancedValidationTest
BodyWithCustomContentTypeTest
PathArgumentsDemoTest
HeaderTest
JSONGetTest
JSONPostTest
ResponseTest
DeleteTest
SSLTest
ParamTest
ConfigTest
ObjectMappingTest
HttpClientConfigTest
UriValidatorTest
LoggingTest

**Comment by ziforigin** [comment]
I'll pick up Header Test

**Comment by DaniilPavlov1** [comment]
I would like to pick up JSONGetTest

**Comment by hellokitties** [comment]
instead of PathArgumentsDemoTest use PathParamITest from rest-assured which more actual

**Comment by ElenaPoduzova** [comment]
All tasks have been completed.
