### ISSUE TITLE
Check compiling on all java versions

### ISSUE THREAD

**Issue by BelAn97** [jdi-testing/jdi-dark#438]

**Comment by EkSemenovaE** [comment]
Were checked:
1. Compiling on **Java SE 7**
> Compiling error
> `Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jdi-dark: Fatal error compiling`
2. Compiling on **Java SE 8u261**
> **OK**
3. Compiling on **Java SE 11 (LTS)** 
> Compiling error
> `Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jdi-dark: Fatal error compiling`
4. Compiling on **Java SE 14 (14.0.2)**
> Compiling error
> `Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jdi-dark: Fatal error compiling`
