### ISSUE TITLE
Ignoring invalid certificates

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-dark#459]
As per @romaha08 feedback:
Вопрос: Как можно в пост запросе, когда мы делаем auth - игнорировать невалидные сертификаты...

**Проблема:** 
При попытке дернуть https://ххх.auth.us-east-1.amazoncognito.com/oauth2/token запрос падает. Ругется на сертификаты
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by AlexeyGirin** [comment]
1. Сделать демо проект которая демонстрирует проблему
2. Связаться с Виталием Духовым - обсудить с ним

**Comment by 1138th** [comment]
Решение проблемы:
Добавить в инициализатор, либо напрямую в рест метод RequestSpecification билдер, напр:

ServiceInit.init(Class.class, new RequestSpecBuilder().setRelaxedHTTPSValidation().build());

Важно: не решается при использовании HostnameVerifier, в частности ALLOW_ALL_HOSTNAME_VERIFIER или подобное.
