### ISSUE TITLE
Verify request logging

### ISSUE THREAD

**Issue by BelAn97** [jdi-testing/jdi-dark#66]
TrelloTest - getCardByShortId():
parameters at 'Query params' instead of 'Path params'.

Request method:	GET
Request URI:	https://api.trello.com/1/boards/5a27e3b62fef5d3a74dca48a/cards/1?key=3445103a21ddca2619eaceb0e833d0db&token=a9b951262e529821308e7ecbc3e4b7cfb14a24fef5ea500a68c69d374009fcc0
Proxy:			<none>
Request params:	<none>
Query params:	key=3445103a21ddca2619eaceb0e833d0db
				token=a9b951262e529821308e7ecbc3e4b7cfb14a24fef5ea500a68c69d374009fcc0
Form params:	<none>
Path params:	<none>
Headers:		Accept=*/*
				Content-Type=application/json; charset=UTF-8
Cookies:		<none>
Multiparts:		<none>
Body:			<none>

**Comment by ElenaPoduzova** [comment]
Query params are correct.
Path params are empty because they are converted to url in public RequestSpecification getSpec().
