### ISSUE TITLE
Move code for jdi-http-cucumber to jdi-dark repository

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-dark#7]
- Name module jdi-dark-bdd
- Move all code and tests from https://github.com/epam/JDI/tree/master/Java/JDI/jdi-http-cucumber
and 
https://github.com/epam/JDI/tree/master/Java/Tests/jdi-http-cucumbertests
- Rename all packages from "jdi-http-cucumber" to "jdi-dark-bdd"
- use jdi-dark dependency instead of old jdi-http

**Comment by BelAn97** [comment]
Code have moved.
