### ISSUE TITLE
Using Lombok for any entity-like objects

### ISSUE THREAD

**Issue by toolateitsme** [jdi-testing/jdi-dark#8]
Is there an possibility to add a lombok? This library will provide many syntax-sugar while implementation?

**Comment by AlexeyGirin** [comment]
Есть сомнения что это возможно в принципе.
@BelAn97 - связаться с @toolateitsme и обсудить суть предложения, если это невозможно - закрыть таску

**Comment by BelAn97** [comment]
Done.
